services:
  - type: web
    name: youtube-downloader-bot-v2
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true
