services:
  - type: web
    name: youtube-download-father-bot
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: BOT_TOKEN
        sync: false
    healthCheckPath: "/"
